version: '3.8'

services:
  web:
    image: webera/apache:latest
    ports:
      - "8080:8080"
    environment:
      - PHP_FPM_HOST=php
      - PHP_FPM_PORT=9000
    volumes:
      - ./src:/var/www/public_html:ro
    depends_on:
      - php
    networks:
      - webera-network

  php:
    image: webera/php:latest
    environment:
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAX_EXECUTION_TIME=60
      - PHP_UPLOAD_MAX_FILESIZE=10M
      - PHP_POST_MAX_SIZE=10M
    volumes:
      - ./src:/var/www/public_html
    networks:
      - webera-network

networks:
  webera-network:
    driver: bridge