---
name: Build Docker Images

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image-path: 
        required: true
        description: 'The path of the image to build'
        type: string

permissions:
    contents: read
    packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: ./${{ inputs.image-path }}
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/wearewebera/public-images/images/${{ inputs.image-path }}:${{ github.sha }}, ghcr.io/wearewebera/public-images/images/${{ inputs.image-path }}:latest
        push: true
