---
name: Build All Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

permissions:
    contents: read
    packages: write

jobs:
  image-base:
    name: "Build Base Image"
    secrets: inherit
    uses: ./.github/workflows/image-base.yml

  image-all:
    strategy:
      matrix:
        image: [apache] #, nginx, ssh, php, python, node
    name: "Build ${{ matrix.image }} Image"
    needs: "image-base"
    secrets: inherit
    uses: ./.github/workflows/image-${{ matrix.image }}.yml
