---
name: Build All Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

permissions:
    contents: read
    packages: write

jobs:
  image-base:
    name: "Build Base Image"
    secrets: inherit
    uses: ./.github/workflows/image-base.yml

# Currently, using Matrix for the uses keyword is not supported.
# We separated each build into its own job.

  image-apache:
    name: "Build Apache Image"
    needs: "image-base"
    secrets: inherit
    uses: ./.github/workflows/image-apache.yml

  image-nginx:
    name: "Build Nginx Image"
    needs: "image-base"
    secrets: inherit
    uses: ./.github/workflows/image-nginx.yml

  image-ssh:
    name: "Build SSH Image"
    needs: "image-base"
    secrets: inherit
    uses: ./.github/workflows/image-ssh.yml

  image-php:
    name: "Build PHP Image"
    needs: "image-base"
    secrets: inherit
    uses: ./.github/workflows/image-php.yml

  image-python:
    name: "Build Python Image"
    needs: "image-base"
    secrets: inherit
    uses: ./.github/workflows/image-python.yml

  image-node:
    name: "Build Node Image"
    needs: "image-base"
    secrets: inherit
    uses: ./.github/workflows/image-nodejs.yml
