---
name: Build Node Image

on:
  workflow_dispatch:
  workflow_call:
  push:
      branches:
        - main
      paths:
        - images/node/**

permissions:
    contents: read
    packages: write

jobs:
  run-image:
    name: "Build Node"
    secrets: inherit
    uses: ./.github/workflows/build.yml
    with:
      image-name: node
      image-path: images/nodejs
