---
name: Build Nodejs Image

on:
  workflow_dispatch:
  workflow_call:
  push:
      branches:
        - main
      paths:
        - images/nodejs/**

permissions:
    contents: read
    packages: write

jobs:
  run-image:
    name: "Build Nodejs"
    secrets: inherit
    uses: ./.github/workflows/build.yml
    with:
      image-name: nodejs
      image-path: images/nodejs
