---
name: Build Go Image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: 'Build and Push Go Image'
    secrets: inherit
    uses: ./.github/workflows/build.yml
    with:
      image-path: images/go
      image-name: go