---
name: Build Wireguard Client Image

on:
  workflow_dispatch:
  workflow_call:
  push:
      branches:
        - main
      paths:
        - images/wireguard-client/**

permissions:
    contents: read
    packages: write

jobs:
  run-image:
    name: "Build Wireguard Client"
    secrets: inherit
    uses: ./.github/workflows/build.yml
    with:
      image-name: wireguard-client
      image-path: images/wireguard-client
