---
name: Build Nginx Image

on:
  workflow_dispatch:
  workflow_call:
  push:
      branches:
        - main
      paths:
        - images/nginx/**

permissions:
    contents: read
    packages: write

jobs:
  run-image:
    name: "Build Nginx"
    secrets: inherit
    uses: ./.github/workflows/build.yml
    with:
      image-name: nginx
      image-path: images/nginx
