---
name: Build Python Image

on:
  workflow_dispatch:
  workflow_call:
  push:
      branches:
        - main
      paths:
        - images/python/**

permissions:
    contents: read
    packages: write

jobs:
  run-image:
    name: "Build Python"
    secrets: inherit
    uses: ./.github/workflows/build.yml
    with:
      image-name: python
      image-path: images/python
